### ISSUE TITLE
can't add repo debian LTS 9.8

### ISSUE THREAD

**Issue by ArticGfx** [daniruiz/flat-remix-gnome#75]
I've installed Debian 9.8 lts and first thing i wanted to do is set gnome to fit my taste.
trying to add the repo and getting this error  
`sudo add-apt-repository ppa:daniruiz/flat-remix Flat Remix themes
 More info: https://launchpad.net/~daniruiz/+archive/ubuntu/flat-remix
Press [ENTER] to continue or ctrl-c to cancel adding it
gpg: keybox '/tmp/tmpla8liv9m/pubring.gpg' created
gpg: /tmp/tmpla8liv9m/trustdb.gpg: trustdb created
gpg: key A074F0583066C9C9: public key "Launchpad PPA for Daniel" imported
gpg: Total number processed: 1
gpg:               imported: 1
gpg: no valid OpenPGP data found.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 688, in addkey_func
    func(**kwargs)
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 386, in add_key
    return apsk.add_ppa_signing_key()
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 273, in add_ppa_signing_key
    cleanup(tmp_keyring_dir)
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 234, in cleanup
    shutil.rmtree(tmp_keyring_dir)
  File "/usr/lib/python3.5/shutil.py", line 480, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/lib/python3.5/shutil.py", line 438, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/usr/lib/python3.5/shutil.py", line 436, in _rmtree_safe_fd
    os.unlink(name, dir_fd=topfd)
FileNotFoundError: [Errno 2] No such file or directory: 'S.gpg-agent.ssh' `

any guess on what the problem came from?

**Comment by daniruiz** [comment]
I've never tested the ppa on debian and I hava no idea wether it should work or not. But you can install it with `make install`

```bash
cd /tmp && rm -rf flat-remix-gnome &&
git clone https://github.com/daniruiz/flat-remix-gnome && cd flat-remix-gnome;
# If you want to change the login wallpaper
# (cd src && ./build.sh --login-background /path/to/image)
sudo make install
```
